---
title: "SCA_Banana_3"
author: "AmolDixit"
date: "7 June 2019"
output: pdf_document
---

```{r cleanup, warning=F}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```


```{r packagesInstall, echo=F, warning=F}
### install packages

# install.packages("igraph")
# install.packages("leaflet")
# install.packages("geosphere")
# install.packages("optrees")
# install.packages("SDMTools")
# install.packages("jsonlite")
# install.packages("dplyr")
# install.packages("RCurl")

pkgs <- c("igraph", "leaflet", "geosphere", "optrees", "jsonlite",
                 "SDMTools", "dplyr","RCurl")
for (i in pkgs) {
 install.packages(pkgs[i])
}

```


```{r loadingLibs, warning=FALSE}
libs <- c("igraph", "leaflet", "geosphere", "optrees", "jsonlite",
                 "SDMTools", "dplyr")
library(pacman)
pacman::p_load(char=libs,install=TRUE,character.only=TRUE)

```

```{r userDefinedFunctions, warning=FALSE}
# Tests whether row vectors are within a matrix; identifies rows in matrix accordingly 
vecInVecSeq <- function(testVectorMatrix, seqVectorMatrix) {
  r <- rep(FALSE,nrow(seqVectorMatrix))
  for (k in 1:nrow(testVectorMatrix)) {
    testElement = testVectorMatrix[k,]
    r <- r | apply(seqVectorMatrix, 1, function(x, test) isTRUE(all.equal(x, test)), testElement)
  }
  return(r)
}


# create distance matrix
mat2list <- function(D) {
  n = dim(D)[1]
  k <- 1
  e <- matrix(ncol = 3,nrow = n*(n-1)/2)
  for (i in 1:(n-1)) {
    for (j in (i+1):n) {
      e[k,] = c(i,j,D[i,j])
      k<-k+1
    }
  }
  return(e)
}


loc <- function (longitude, latitude) 
{
  location <- list()
  url <- paste0("http://photon.komoot.de/reverse?lon=", 
                longitude, "&lat=", latitude)
    data <- getURL(url)
    returned_data <- fromJSON(data)
    city <- returned_data$features$properties$city
    country <- returned_data$features$properties$country
    location <- paste(city, country, sep = ", ")
    return(location)
}
```


```{r distributionCentresList, warning=FALSE}
# Cities to Supply
nname <- c("Lisbon","Moscow","Warsaw","Helsinki","Brussels","Paris",
           "Oslo","Stockholm","Rome","Vienna")
# Latitude and Longitude information for these cities. From Google Maps
lat <- as.numeric(c('38.7436266','55.5815243','52.2330269','60.11021','50.838833',
         '48.8589507','59.8939529','59.326242','41.9102415','48.2208286'))

long <- as.numeric(c('-9.1602032','36.8250949','20.7810075','24.7385001','4.2233201','2.2770197',
          '10.6450334','17.8419693','12.3959115','16.2399746'))
```

```{r combinedInfoInVec, warning=FALSE}
v <- data.frame(ids = 1:10,
                name=nname,
                 lat=lat,
                 long=long)
```

```{r CitiesOnMap, warning=FALSE}
# DistributionCentres on a Map
leaflet(data=v[1:10,]) %>% addTiles() %>%
  addMarkers(lng=v$long, lat=v$lat, popup=v$name)

# Linkages between DistributionCentres shown on a Map
leaflet(data=v[1:10,]) %>% addTiles() %>%
  addMarkers(lng=v$long, lat=v$lat, popup=v$name) %>%
  addPolylines(lng=v$long, lat=v$lat, popup=v$name)
```


```{r geodesicDist, warning=FALSE}
# The Geodesic distance is chosen because of its accuracy.

# geodesic distance: Highly accurate estimate of the shortest distance between two points on an ellipsoid (default is WGS84 ellipsoid). The shortest path between two points on an ellipsoid is called the geodesic.

longlat <- data.frame(v$long, v$lat)

mDist <- distm(longlat, fun=distGeo) # in meters

kmDist <- mat2list(mDist/1000) #km
kmDist <- kmDist[order(kmDist[,3]),] #sort edges
```



```{r MST, warning=FALSE}
# creating Minimum Spanning Tree (Kruskal's algroithm)
mst <- getMinimumSpanningTree(v$name, round(kmDist), algorithm = "Kruskal",
                              show.data = TRUE, show.graph = TRUE, check.graph = FALSE)

# creating a graph of MST
graph <- graph.data.frame(kmDist[,1:2],directed = FALSE, vertices = v)
E(graph)$weight <- kmDist[,3]
mstgraph <- minimum.spanning.tree(graph)

par(mfrow=c(1,2), mar=c(0,1,0.75,0)) 
plot(graph,vertex.label=nname)
plot(mstgraph,vertex.shape="none",edge.label=round(E(mstgraph)$weight))
plot(mstgraph,vertex.shape="none")

```


```{r cluterCreation, warning=FALSE}
# creating k clusters from full mst graph
k <- 3
e.mst <- get.edges(mstgraph,1:ecount(mstgraph)) # matrix of edges of MST
e.clust <- get.edges(mstgraph,1:(ecount(mstgraph)-k+1)) # matrix of edges of k cluster
clust_idx <- vecInVecSeq(e.clust, e.mst) # row indicis cluster in MST

ecol <- rep("grey80", ecount(mstgraph)) # default edge colour
ecol[clust_idx] <- "green" # colour for clusters
ew <- rep(2,ecount(mstgraph)) # default edge width
ew[clust_idx] <- 5 # width for clust edges

par(mfrow=c(1,1), mar=c(0,1,0.75,0)) 

plot(mstgraph, vertex.shape="none",vertex.label.cex=0.85,
     edge.color=ecol, edge.width=ew,edge.label.cex=0.85,
     edge.label=round(E(mstgraph)$weight))
```


```{r warehouseLocations, warning=FALSE}
# Finding the warehouse locations in Clusters

cid <- c(2,1,1,1,3,3,1,1,1,1)
k <- length(unique(cid))
v <- data.frame(v,cid)

for(i in 1:k){
  vi <- v[v$cid==i,]
  centrei <- COGravity(vi$long,vi$lat)
  
  leaflet(data=vi[1:nrow(vi),]) %>% addTiles() %>%
    addMarkers(lng=vi$long, lat=vi$lat, popup=vi$name) %>%
    addAwesomeMarkers(lng=centrei[1], lat=centrei[3], 
                      icon = awesomeIcons(markerColor = "red"),
                      popup=paste("Center of Cluster ", i))
  
  location <- loc(longitude=centrei[1], latitude=centrei[3])
  
  print(paste("Center of Cluster", i, "is at longitude = ", centrei[1],
              "and latitude = ", centrei[3], "which is at ", location))
}
```



```{r *****, warning=FALSE}

```